services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=server
      - POSTGRES_DB=postgres
    networks:
      - app-network
    volumes:
      - learner-vol:/var/lib/postgresql/data

  auth:
    build: ./learner-auth
    ports:
      - "8000:8000"
    networks:
      - app-network

  app:
    build: ./learner
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=server
      - DB_NAME=postgres
      - AUTH_HOST=auth
    depends_on:
      - db
      - auth
    networks:
      - app-network

networks:
  app-network:

volumes:
  learner-vol:
    driver: local
    driver_opts:
      type: none
      device: ./learner-vol
      o: bind
