services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=server
      - POSTGRES_DB=postgres
    networks:
      - app-network
    volumes:
      - vibrox-vol:/var/lib/postgresql/data

  logger:
    build: ./vibrox-echo
    ports:
      - "9000:9000"
    networks:
      - app-network
    volumes:
      - ./vibrox-echo/logs:/app/logs

  auth:
    build: ./vibrox-auth
    ports:
      - "8000:8000"
    networks:
      - app-network

  app:
    build: ./vibrox-core
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=server
      - DB_NAME=postgres
      - AUTH_HOST=auth:8000
      - LOGGER_HOST=logger:9000
    depends_on:
      - db
      - logger
      - auth
    networks:
      - app-network

networks:
  app-network:

volumes:
  vibrox-vol:
    driver: local
    driver_opts:
      type: none
      device: ./vibrox-vol
      o: bind
  vibrox-echo-vol:
    driver: local
    driver_opts:
      type: none
      device: ./vibrox-echo/logs
      o: bind
