apiVersion: apps/v1
kind: Deployment
metadata:
  name: learner-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: learner-auth
  template:
    metadata:
      labels:
        app: learner-auth
    spec:
      containers:
        - name: learner-auth
          image: viburoshin25/learner-auth:latest
          imagePullPolicy: Always
