apiVersion: apps/v1
kind: Deployment
metadata:
  name: vibrox-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vibrox-auth
  template:
    metadata:
      labels:
        app: vibrox-auth
    spec:
      containers:
        - name: vibrox-auth
          image: viburoshin25/vibrox-auth:latest
          imagePullPolicy: Always
