apiVersion: apps/v1
kind: Deployment
metadata:
  name: vibrox-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vibrox-db
  template:
    metadata:
      labels:
        app: vibrox-db
    spec:
      containers:
        - name: vibrox-db
          image: postgres:latest
          imagePullPolicy: Always
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: hostpath-pv
      volumes:
        - name: hostpath-pv
          persistentVolumeClaim:
            claimName: hostpath-pvc
