apiVersion: apps/v1
kind: Deployment
metadata:
  name: vibrox-echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vibrox-echo
  template:
    metadata:
      labels:
        app: vibrox-echo
    spec:
      containers:
        - name: vibrox-echo
          image: viburoshin25/vibrox-echo:latest
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /app/logs
              name: logger-pv
      volumes:
        - name: logger-pv
          persistentVolumeClaim:
            claimName: logger-pvc
