apiVersion: v1
kind: PersistentVolume
metadata:
  name: logger-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: "/mnt/logger-logs"
